import type { Metadata } from 'next'
import { Demo } from './components/demo'
import { Demo2 } from './components/demo2'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header><Demo /><Demo2 /></header>
        {children}
      </body>
    </html>
  )
}
